### ISSUE TITLE
integration doesn't create sensor - Custom element doesn't exist: content-card-another-mvg

### ISSUE THREAD

**Issue by Git-Vi** [Nisbo/another_mvg#12]
Hello, I added the integration to HA and for some reason it doesn't create sensor
 
Custom element doesn't exist: content-card-another-mvg.
type: custom:content-card-another-mvg
entity: sensor.puchheim_another_mvg

Home assistant 2024.9.1
Another MVG 1.5 installed via HACS 2..0.1

Settings —> Devices & Services —> Entities --> search mask --> enter: puchheim
nothing found 

configuration.yaml
```
sensor:
  - platform: another_mvg
    name: "puchheim_another_mvg"
    globalid: "de:09179:6170"
    hidedestination: "Fürstenfeldbruck,Geltendorf,Buchenau,Grafrath"
    limit: 15
    transporttypes: "SBAHN"
```
