### ISSUE TITLE
Content Card not working

### ISSUE THREAD

**Issue by joemfe** [Nisbo/another_mvg#19]
First of all, thank you so much for you contribution to HA! This looks like a really cool integration, but no matter what I try, I cannot get the cards to work. I tried the following:

- both installation methods (HACS store and manual cloning the git repo)
- restarted HA multiple times
- cleared the browser cache
- different browsers
- private browser windows

But once I try to add one of the two cards I get this error, that you already mention in you README.md

![image](https://github.com/user-attachments/assets/d8de3184-8671-4599-95d7-b4769623e6cd)

Maybe the cards need to be added to configuration.yaml? With other HACS features (e.g. the better thermostat UI card) I had to add the path to JavaScript files there like this:

```
lovelace:
  mode: yaml
  resources:
    - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.js
      type: module
    - url: /local/vertical-stack-in-card.js?v=0.4.1
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/mini-graph-card-bundle.js?v=0.11.0
      type: module
    - url: /hacsfiles/better-thermostat-ui-card/better-thermostat-ui-card.js
      type: module
    #- url: /hacsfiles/content-card-another-mvg-big/content-card-another-mvg-big.js
    #  type: module
    #- url: /hacsfiles/content-card-another-mvg/content-card-another-mvg.js
    #  type: module
    #- url: /config/custom_components/another_mvg/frontend/content-card-another-mvg.js
    #  type: module
    #- url: /config/custom_components/another_mvg/frontend/content-card-another-mvg-big.js
    #  type: module
```

I already tried the commented lines, but none worked for me. Any ideas what could be the problem?
